import Home from './Home'
import About from './About'
import Error from './Error'
import Ai from './Ai'
import Ml from './Ml'
import Cns from './Cns'
import Pe from './Pe'
import OE from './Oe'
import Cd from './Cd'
import Pcc from './Pcc'
import Sse from './Sse'
import Fsd from './Fsd'
import Submit from './Submit'
export{Home,About,Error,Ai,Ml,Cns,Pe,OE,Cd,Pcc,Sse,Fsd,Submit}